### ISSUE TITLE
[v19.08.2-3.0.3] Videos are sporadically hidden on Home page

### ISSUE THREAD

**Issue by CaptainMorgan96** [qnblackcat/uYouPlus#1522]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS version: 16.7.8
- Device model: iPhone 8
- Sideload tool: Altserver

### Describe the issue

Videos on the default home page under All category pop in and out as I scroll down. I had changed some settings around months ago when I first got the app, but I didn’t get this problem until recently. The only solution I can think of is deleting and redownloading the app.

https://github.com/qnblackcat/uYouPlus/assets/35874148/8b0ac5fe-60ee-4da1-93a0-9979b35537bd

### Steps to reproduce

I honestly can’t remember the settings I changed from default. I’m just gonna reinstall uYouPlus and see if it fixes itself

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

**Comment by CaptainMorgan96** [comment]
Update: Reinstalling the app from scratch didn't fix it. It had nothing to do with my settings, at least as far as I can tell. If anyone else has had this issue please help out

**Comment by Yunogamer** [comment]
> It's the internal Adblock YouTube has implemented. As far as I know there is no fix as of now!

ytlite plus works fine..

**Comment by Yunogamer** [comment]
it does here, on 19.26.5 anyway

**Comment by iqbal1992** [comment]
I am using19.26.5 on my iPhone 12 pro max with iOS dev beta 3 and everything working great so far.

**Comment by Maxokaan** [comment]
I have the same issue. Latest version, but can’t see any videos on my main feed. While good for my YT addiction, I’d like to see my feed. My issues persists though, it’s not occasionally like OP

**Comment by PoomSmart** [comment]
Fixed in the latest commit.

**Comment by CaptainMorgan96** [comment]
> Fixed in the latest commit.

Sorry, I'm still new to github. I saw your updates, but how do I get download that new version of uYou with your fix? I originally went to the website https://uyouplus.com/ If I go to that site right now, it still shows a download for version 19.08.2-3.0.3, which is what I already had before. If I download it now, will it have your most recent commit?

**Comment by iqbal1992** [comment]
> > Fixed in the latest commit.
> 
> 
> 
> Sorry, I'm still new to github. I saw your updates, but how do I get download that new version of uYou with your fix? I originally went to the website https://uyouplus.com/ If I go to that site right now, it still shows a download for version 19.08.2-3.0.3, which is what I already had before. If I download it now, will it have your most recent commit?

You have to build the ipa file. See the Build section of the repository and you will know.

**Comment by CaptainMorgan96** [comment]
> Fixed in the latest commit.

I have been trying for literal months to build the ipa using the wiki, and it's always failed because of (I think) the cloud link to the decrypted ipa. I'm getting an error that I'm using Mac OS 12 even though I'm on a windows laptop, and the error starts at the ipa link in the log. Other than that I'm lost. Searching for tutorials on what I'm supposed to do has been infuriating and draining and I've tried my best. Is there anywhere I can just download the final product? Can you please upload it to the uyouplus website?
