### ISSUE TITLE
[Bug] <PiP not working on iPhone XR latest IOS version>

### ISSUE THREAD

**Issue by difman62** [qnblackcat/uYouPlus#788]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [x] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 16.2
- Device model: iPhone XR
- Sideload tool (AltStore, Sideloadly, TrollStore,...): 3uTools
- The specific version of uYouPlus (**latest** or **newest** is NOT a version number!): v17.48.2-2.1

### Describe the bug

PiP function just doesn't work on the app. However, when swiped out of the app, the audio of the video is still playing at the background. uYouPiP did work tho. 

Also, this is not about the bug, how do you toggle a video playback quality so that everytime, you don't have to select the quality?

https://user-images.githubusercontent.com/121245283/209171226-eda70a64-061f-40f4-a629-78e1420620c2.mp4

### Steps to reproduce the issue

1. Open any video
2. Click the PiP button under the video player
3. There you go, the whole app just crash (for me tho)

### Crash log (if the app crashes)

```shell
{"app_name":"YouTube","timestamp":"2022-12-22 23:52:28.00 +0800","app_version":"17.48.2","slice_uuid":"8a68a1e5-e304-3358-ad1a-e6fcc2db849d","build_version":"17.48.2","platform":2,"bundleID":"com.google.ios.youtube.2CCV7ZTX7D","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"iPhone OS 16.2 (20C65)","roots_installed":0,"name":"YouTube","incident_id":"E1500822-B209-4440-A906-9FB43467F038"}
{
  "uptime" : 240000,
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "iPhone11,8",
  "coalitionID" : 1176,
  "osVersion" : {
    "isEmbedded" : true,
    "train" : "iPhone OS 16.2",
    "releaseType" : "User",
    "build" : "20C65"
  },
  "captureTime" : "2022-12-22 23:52:27.1977 +0800",
  "incident" : "E1500822-B209-4440-A906-9FB43467F038",
  "pid" : 30502,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2022-12-22 23:52:13.7055 +0800",
  "procStartAbsTime" : 5936957592069,
  "procExitAbsTime" : 5937281197960,
  "procName" : "YouTube",
  "procPath" : "\/private\/var\/containers\/Bundle\/Application\/C2AE7A3D-01CC-4AD4-8227-F9DE4D7F94D8\/YouTube.app\/YouTube",
  "bundleInfo" : {"CFBundleShortVersionString":"17.48.2","CFBundleVersion":"17.48.2","CFBundleIdentifier":"com.google.ios.youtube.2CCV7ZTX7D","DTAppStoreToolsBuild":"14B44"},
  "storeInfo" : {"deviceIdentifierForVendor":"96F7406C-B83F-4DBD-AA1C-8C6EC0F61806","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.google.ios.youtube.2CCV7ZTX7D",
  "crashReporterKey" : "d018f085b062f5fbf533b923f9e94ffd503e0e54",
  "ldm" : 1,
  "wasUnlockedSinceBoot" : 1,
  "isLocked" : 0,
  "throttleTimeout" : 2147483647,
  "basebandVersion" : "5.01.01",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "ktriageinfo" : "VM - pmap_enter retried due to resource shortage\nVM - pmap_enter retried due to resource shortage\nVM - pmap_enter retried due to resource shortage\nVM - pmap_enter retried due to resource shortage\nVM - pmap_enter retried due to resource shortage\n",
  "asi" : {"libsystem_c.dylib":["abort() called"]},
  "lastExceptionBacktrace" : [{"imageOffset":40520,"symbol":"__exceptionPreprocess","symbolLocation":164,"imageIndex":5},{"imageOffset":96472,"symbol":"objc_exception_throw","symbolLocation":60,"imageIndex":4},{"imageOffset":1533812,"symbol":"-[NSException init]","symbolLocation":0,"imageIndex":5},{"imageOffset":5679576,"symbol":"-[NSObject(NSKeyValueCoding) valueForUndefinedKey:]","symbolLocation":192,"imageIndex":10},{"imageOffset":21332,"symbol":"-[NSObject(NSKeyValueCoding) valueForKey:]","symbolLocation":316,"imageIndex":10},{"imageOffset":22820,"imageIndex":15},{"imageOffset":779404,"symbol":"-[UIGestureRecognizerTarget _sendActionWithGestureRecognizer:]","symbolLocation":156,"imageIndex":7},{"imageOffset":4374716,"symbol":"_UIGestureRecognizerSendTargetActions","symbolLocation":92,"imageIndex":7},{"imageOffset":1727536,"symbol":"_UIGestureRecognizerSendActions","symbolLocation":272,"imageIndex":7},{"imageOffset":550412,"symbol":"-[UIGestureRecognizer _updateGestureForActiveEvents]","symbolLocation":484,"imageIndex":7},{"imageOffset":1254752,"symbol":"_UIGestureEnvironmentUpdate","symbolLocation":2436,"imageIndex":7},{"imageOffset":10197308,"symbol":"-[UIGestureEnvironment _deliverEvent:toGestureRecognizers:usingBlock:]","symbolLocation":288,"imageIndex":7},{"imageOffset":1011744,"symbol":"-[UIGestureEnvironment _updateForEvent:window:]","symbolLocation":188,"imageIndex":7},{"imageOffset":1030520,"symbol":"-[UIWindow sendEvent:]","symbolLocation":3268,"imageIndex":7},{"imageOffset":32553060,"imageIndex":11},{"imageOffset":1027144,"symbol":"-[UIApplication sendEvent:]","symbolLocation":672,"imageIndex":7},{"imageOffset":1024772,"symbol":"__dispatchPreprocessedEventFromEventQueue","symbolLocation":7084,"imageIndex":7},{"imageOffset":1318936,"symbol":"__processEventQueue","symbolLocation":5632,"imageIndex":7},{"imageOffset":4498780,"symbol":"__eventFetcherSourceCallback","symbolLocation":224,"imageIndex":7},{"imageOffset":876340,"symbol":"__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__","symbolLocation":28,"imageIndex":5},{"imageOffset":926476,"symbol":"__CFRunLoopDoSource0","symbolLocation":176,"imageIndex":5},{"imageOffset":418256,"symbol":"__CFRunLoopDoSources0","symbolLocation":244,"imageIndex":5},{"imageOffset":506764,"symbol":"__CFRunLoopRun","symbolLocation":836,"imageIndex":5},{"imageOffset":528064,"symbol":"CFRunLoopRunSpecific","symbolLocation":612,"imageIndex":5},{"imageOffset":4968,"symbol":"GSEventRunModal","symbolLocation":164,"imageIndex":6},{"imageOffset":3807340,"symbol":"-[UIApplication _run]","symbolLocation":888,"imageIndex":7},{"imageOffset":3806416,"symbol":"UIApplicationMain","symbolLocation":340,"imageIndex":7},{"imageOffset":562836,"imageIndex":8},{"imageOffset":88416,"symbol":"start","symbolLocation":2528,"imageIndex":9}],
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":1640822,"threadState":{"x":[{"value":0},{"value":0},{"value":0},{"value":0},{"value":7884566773},{"value":6164934848},{"value":110},{"value":0},{"value":3697759452251789589},{"value":3697759448723598549},{"value":512},{"value":11},{"value":11},{"value":2095104},{"value":2043},{"value":2155952218},{"value":328},{"value":8024503744,"symbolLocation":0,"symbol":"_main_thread"},{"value":0},{"value":6},{"value":259},{"value":8024503968,"symbolLocation":224,"symbol":"_main_thread"},{"value":8045596736,"symbolLocation":0,"symbol":"__kCFAllocatorSystemDefault"},{"value":10794060032},{"value":1},{"value":1},{"value":1},{"value":0},{"value":7131601024,"symbolLocation":0,"symbol":"tlv_get_addr"}],"flavor":"ARM_THREAD_STATE64","lr":{"value":7885341100},"cpsr":{"value":1073741824},"fp":{"value":6164934704},"sp":{"value":6164934672},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":7609446752,"matchesCrashFrame":1},"far":{"value":7884492308}},"queue":"com.apple.main-thread","frames":[{"imageOffset":45408,"symbol":"__pthread_kill","symbolLocation":8,"imageIndex":0},{"imageOffset":29100,"symbol":"pthread_kill","symbolLocation":268,"imageIndex":1},{"imageOffset":134284,"symbol":"abort","symbolLocation":180,"imageIndex":2},{"imageOffset":72588,"symbol":"abort_message","symbolLocation":132,"imageIndex":3},{"imageOffset":6784,"symbol":"demangling_terminate_handler()","symbolLocation":336,"imageIndex":3},{"imageOffset":122172,"symbol":"_objc_terminate()","symbolLocation":144,"imageIndex":4},{"imageOffset":69416,"symbol":"std::__terminate(void (*)())","symbolLocation":20,"imageIndex":3},{"imageOffset":81612,"symbol":"__cxa_rethrow","symbolLocation":148,"imageIndex":3},{"imageOffset":104116,"symbol":"objc_exception_rethrow","symbolLocation":44,"imageIndex":4},{"imageOffset":528260,"symbol":"CFRunLoopRunSpecific","symbolLocation":808,"imageIndex":5},{"imageOffset":4968,"symbol":"GSEventRunModal","symbolLocation":164,"imageIndex":6},{"imageOffset":3807340,"symbol":"-[UIApplication _run]","symbolLocation":888,"imageIndex":7},{"imageOffset":3806416,"symbol":"UIApplicationMain","symbolLocation":340,"imageIndex":7},{"imageOffset":562836,"imageIndex":8},{"imageOffset":88416,"symbol":"start","symbolLocation":2528,"imageIndex":9}]},{"id":1640844,"frames":[{"imageOffset":2960,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":1640846,"name":"com.apple.uikit.eventfetch-thread","frames":[{"imageOffset":19112,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":0},{"imageOffset":94148,"symbol":"mach_msg2_internal","symbolLocation":80,"imageIndex":0},{"imageOffset":94724,"symbol":"mach_msg_overwrite","symbolLocation":388,"imageIndex":0},{"imageOffset":20460,"symbol":"mach_msg","symbolLocation":24,"imageIndex":0},{"imageOffset":502484,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":160,"imageIndex":5},{"imageOffset":507160,"symbol":"__CFRunLoopRun","symbolLocation":1232,"imageIndex":5},{"imageOffset":528064,"symbol":"CFRunLoopRunSpecific","symbolLocation":612,"imageIndex":5},{"imageOffset":270548,"symbol":"-[NSRunLoop(NSRunLoop) runMode:beforeDate:]","symbolLocation":212,"imageIndex":10},{"imageOffset":270268,"symbol":"-[NSRunLoop(NSRunLoop) runUntilDate:]","symbolLocation":64,"imageIndex":10},{"imageOffset":5072684,"symbol":"-[UIEventFetcher threadMain]","symbolLocation":436,"imageIndex":7},{"imageOffset":374184,"symbol":"__NSThread__start__","symbolLocation":716,"imageIndex":10},{"imageOffset":5836,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":1},{"imageOffset":2980,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]},{"id":1640847,"frames":[{"imageOffset":2960,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":1640848,"frames":[{"imageOffset":2960,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":1640861,"frames":[{"imageOffset":2960,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":1640862,"frames":[{"imageOffset":2960,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":1640867,"frames":[{"imageOffset":2960,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":1640868,"frames":[{"imageOffset":2960,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":1640872,"name":"unnamed","frames":[{"imageOffset":21372,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":0},{"imageOffset":32876,"symbol":"_pthread_cond_wait","symbolLocation":1232,"imageIndex":1},{"imageOffset":80539160,"imageIndex":11},{"imageOffset":10277436,"imageIndex":11},{"imageOffset":80541824,"imageIndex":11},{"imageOffset":80951956,"imageIndex":11},{"imageOffset":80542852,"imageIndex":11},{"imageOffset":78613204,"symbol":"youtube::client::blocks::runtime::ts::JSInstanceDisposer::Run()","symbolLocation":120,"imageIndex":11},{"imageOffset":78817560,"imageIndex":11},{"imageOffset":5836,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":1},{"imageOffset":2980,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]},{"id":1640904,"name":"com.apple.NSURLConnectionLoader","frames":[{"imageOffset":19112,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":0},{"imageOffset":94148,"symbol":"mach_msg2_internal","symbolLocation":80,"imageIndex":0},{"imageOffset":94724,"symbol":"mach_msg_overwrite","symbolLocation":388,"imageIndex":0},{"imageOffset":20460,"symbol":"mach_msg","symbolLocation":24,"imageIndex":0},{"imageOffset":502484,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":160,"imageIndex":5},{"imageOffset":507160,"symbol":"__CFRunLoopRun","symbolLocation":1232,"imageIndex":5},{"imageOffset":528064,"symbol":"CFRunLoopRunSpecific","symbolLocation":612,"imageIndex":5},{"imageOffset":2457720,"imageIndex":12},{"imageOffset":374184,"symbol":"__NSThread__start__","symbolLocation":716,"imageIndex":10},{"imageOffset":5836,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":1},{"imageOffset":2980,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]},{"id":1640915,"frames":[{"imageOffset":2960,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":1640916,"frames":[{"imageOffset":2960,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":1640924,"frames":[{"imageOffset":2960,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":1640934,"name":"com.apple.CFSocket.private","frames":[{"imageOffset":22028,"symbol":"__select","symbolLocation":8,"imageIndex":0},{"imageOffset":833188,"symbol":"__CFSocketManager","symbolLocation":636,"imageIndex":5},{"imageOffset":5836,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":1},{"imageOffset":2980,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]},{"id":1640942,"name":"ThreadPoolServiceThread","frames":[{"imageOffset":19112,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":0},{"imageOffset":94148,"symbol":"mach_msg2_internal","symbolLocation":80,"imageIndex":0},{"imageOffset":94724,"symbol":"mach_msg_overwrite","symbolLocation":388,"imageIndex":0},{"imageOffset":20460,"symbol":"mach_msg","symbolLocation":24,"imageIndex":0},{"imageOffset":502484,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":160,"imageIndex":5},{"imageOffset":507160,"symbol":"__CFRunLoopRun","symbolLocation":1232,"imageIndex":5},{"imageOffset":528064,"symbol":"CFRunLoopRunSpecific","symbolLocation":612,"imageIndex":5},{"imageOffset":270548,"symbol":"-[NSRunLoop(NSRunLoop) runMode:beforeDate:]","symbolLocation":212,"imageIndex":10},{"imageOffset":47664264,"imageIndex":11},{"imageOffset":47658108,"imageIndex":11},{"imageOffset":47359964,"imageIndex":11},{"imageOffset":47155744,"imageIndex":11},{"imageOffset":47503512,"imageIndex":11},{"imageOffset":47415688,"imageIndex":11},{"imageOffset":47503808,"imageIndex":11},{"imageOffset":47635752,"imageIndex":11},{"imageOffset":5836,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":1},{"imageOffset":2980,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]},{"id":1640943,"name":"ThreadPoolForegroundWorker","frames":[{"imageOffset":19112,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":0},{"imageOffset":94148,"symbol":"mach_msg2_internal","symbolLocation":80,"imageIndex":0},{"imageOffset":94724,"symbol":"mach_msg_overwrite","symbolLocation":388,"imageIndex":0},{"imageOffset":20460,"symbol":"mach_msg","symbolLocation":24,"imageIndex":0},{"imageOffset":47672600,"imageIndex":11},{"imageOffset":47453116,"imageIndex":11},{"imageOffset":47456072,"imageIndex":11},{"imageOffset":47455164,"imageIndex":11},{"imageOffset":47454896,"imageIndex":11},{"imageOffset":47635752,"imageIndex":11},{"imageOffset":5836,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":1},{"imageOffset":2980,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]},{"id":1640944,"name":"ThreadPoolBackgroundWorker","frames":[{"imageOffset":19112,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":0},{"imageOffset":94148,"symbol":"mach_msg2_internal","symbolLocation":80,"imageIndex":0},{"imageOffset":94724,"symbol":"mach_msg_overwrite","symbolLocation":388,"imageIndex":0},{"imageOffset":20460,"symbol":"mach_msg","symbolLocation":24,"imageIndex":0},{"imageOffset":47672600,"imageIndex":11},{"imageOffset":47453116,"imageIndex":11},{"imageOffset":47455556,"imageIndex":11},{"imageOffset":47455032,"imageIndex":11},{"imageOffset":47454944,"imageIndex":11},{"imageOffset":47635752,"imageIndex":11},{"imageOffset":5836,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":1},{"imageOffset":2980,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]},{"id":1640945,"name":"NetworkConfigWatcher","frames":[{"imageOffset":19112,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":0},{"imageOffset":94148,"symbol":"mach_msg2_internal","symbolLocation":80,"imageIndex":0},{"imageOffset":94724,"symbol":"mach_msg_overwrite","symbolLocation":388,"imageIndex":0},{"imageOffset":20460,"symbol":"mach_msg","symbolLocation":24,"imageIndex":0},{"imageOffset":502484,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":160,"imageIndex":5},{"imageOffset":507160,"symbol":"__CFRunLoopRun","symbolLocation":1232,"imageIndex":5},{"imageOffset":528064,"symbol":"CFRunLoopRunSpecific","symbolLocation":612,"imageIndex":5},{"imageOffset":270548,"symbol":"-[NSRunLoop(NSRunLoop) runMode:beforeDate:]","symbolLocation":212,"imageIndex":10},{"imageOffset":47664264,"imageIndex":11},{"imageOffset":47658108,"imageIndex":11},{"imageOffset":47359964,"imageIndex":11},{"imageOffset":47155744,"imageIndex":11},{"imageOffset":47503512,"imageIndex":11},{"imageOffset":47503808,"imageIndex":11},{"imageOffset":47635752,"imageIndex":11},{"imageOffset":5836,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":1},{"imageOffset":2980,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]},{"id":1640946,"name":"network","frames":[{"imageOffset":19112,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":0},{"imageOffset":94148,"symbol":"mach_msg2_internal","symbolLocation":80,"imageIndex":0},{"imageOffset":94724,"symbol":"mach_msg_overwrite","symbolLocation":388,"imageIndex":0},{"imageOffset":20460,"symbol":"mach_msg","symbolLocation":24,"imageIndex":0},{"imageOffset":502484,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":160,"imageIndex":5},{"imageOffset":507160,"symbol":"__CFRunLoopRun","symbolLocation":1232,"imageIndex":5},{"imageOffset":528064,"symbol":"CFRunLoopRunSpecific","symbolLocation":612,"imageIndex":5},{"imageOffset":270548,"symbol":"-[NSRunLoop(NSRunLoop) runMode:beforeDate:]","symbolLocation":212,"imageIndex":10},{"imageOffset":47664264,"imageIndex":11},{"imageOffset":47658108,"imageIndex":11},{"imageOffset":47359964,"imageIndex":11},{"imageOffset":47155744,"imageIndex":11},{"imageOffset":47503512,"imageIndex":11},{"imageOffset":47503808,"imageIndex":11},{"imageOffset":47635752,"imageIndex":11},{"imageOffset":5836,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":1},{"imageOffset":2980,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]},{"id":1640947,"name":"Network File Thread","frames":[{"imageOffset":19112,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":0},{"imageOffset":94148,"symbol":"mach_msg2_internal","symbolLocation":80,"imageIndex":0},{"imageOffset":94724,"symbol":"mach_msg_overwrite","symbolLocation":388,"imageIndex":0},{"imageOffset":20460,"symbol":"mach_msg","symbolLocation":24,"imageIndex":0},{"imageOffset":502484,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":160,"imageIndex":5},{"imageOffset":507160,"symbol":"__CFRunLoopRun","symbolLocation":1232,"imageIndex":5},{"imageOffset":528064,"symbol":"CFRunLoopRunSpecific","symbolLocation":612,"imageIndex":5},{"imageOffset":47663336,"imageIndex":11},{"imageOffset":47658108,"imageIndex":11},{"imageOffset":47359964,"imageIndex":11},{"imageOffset":47155744,"imageIndex":11},{"imageOffset":47503512,"imageIndex":11},{"imageOffset":47503808,"imageIndex":11},{"imageOffset":47635752,"imageIndex":11},{"imageOffset":5836,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":1},{"imageOffset":2980,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]},{"id":1640948,"name":"ThreadPoolForegroundWorker","frames":[{"imageOffset":19112,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":0},{"imageOffset":94148,"symbol":"mach_msg2_internal","symbolLocation":80,"imageIndex":0},{"imageOffset":94724,"symbol":"mach_msg_overwrite","symbolLocation":388,"imageIndex":0},{"imageOffset":20460,"symbol":"mach_msg","symbolLocation":24,"imageIndex":0},{"imageOffset":47672600,"imageIndex":11},{"imageOffset":47453116,"imageIndex":11},{"imageOffset":47455556,"imageIndex":11},{"imageOffset":47455164,"imageIndex":11},{"imageOffset":47454896,"imageIndex":11},{"imageOffset":47635752,"imageIndex":11},{"imageOffset":5836,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":1},{"imageOffset":2980,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]},{"id":1640949,"name":"com.google.hamplayer.RenderThread","frames":[{"imageOffset":19112,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":0},{"imageOffset":94148,"symbol":"mach_msg2_internal","symbolLocation":80,"imageIndex":0},{"imageOffset":94724,"symbol":"mach_msg_overwrite","symbolLocation":388,"imageIndex":0},{"imageOffset":20460,"symbol":"mach_msg","symbolLocation":24,"imageIndex":0},{"imageOffset":502484,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":160,"imageIndex":5},{"imageOffset":507160,"symbol":"__CFRunLoopRun","symbolLocation":1232,"imageIndex":5},{"imageOffset":528064,"symbol":"CFRunLoopRunSpecific","symbolLocation":612,"imageIndex":5},{"imageOffset":806116,"symbol":"CFRunLoopRun","symbolLocation":64,"imageIndex":5},{"imageOffset":35319348,"imageIndex":11},{"imageOffset":374184,"symbol":"__NSThread__start__","symbolLocation":716,"imageIndex":10},{"imageOffset":5836,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":1},{"imageOffset":2980,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]},{"id":1640950,"name":"com.apple.coremedia.rootQueue.47","frames":[{"imageOffset":19004,"symbol":"semaphore_timedwait_trap","symbolLocation":8,"imageIndex":0},{"imageOffset":17908,"symbol":"_dispatch_sema4_timedwait","symbolLocation":64,"imageIndex":13},{"imageOffset":19444,"symbol":"_dispatch_semaphore_wait_slow","symbolLocation":76,"imageIndex":13},{"imageOffset":88128,"symbol":"_dispatch_worker_thread","symbolLocation":324,"imageIndex":13},{"imageOffset":5836,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":1},{"imageOffset":2980,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]},{"id":1640951,"name":"com.apple.coremedia.rootQueue.47","frames":[{"imageOffset":19004,"symbol":"semaphore_timedwait_trap","symbolLocation":8,"imageIndex":0},{"imageOffset":17908,"symbol":"_dispatch_sema4_timedwait","symbolLocation":64,"imageIndex":13},{"imageOffset":19444,"symbol":"_dispatch_semaphore_wait_slow","symbolLocation":76,"imageIndex":13},{"imageOffset":88128,"symbol":"_dispatch_worker_thread","symbolLocation":324,"imageIndex":13},{"imageOffset":5836,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":1},{"imageOffset":2980,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]},{"id":1640954,"name":"com.apple.coremedia.rootQueue.47","frames":[{"imageOffset":19004,"symbol":"semaphore_timedwait_trap","symbolLocation":8,"imageIndex":0},{"imageOffset":17908,"symbol":"_dispatch_sema4_timedwait","symbolLocation":64,"imageIndex":13},{"imageOffset":19444,"symbol":"_dispatch_semaphore_wait_slow","symbolLocation":76,"imageIndex":13},{"imageOffset":88128,"symbol":"_dispatch_worker_thread","symbolLocation":324,"imageIndex":13},{"imageOffset":5836,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":1},{"imageOffset":2980,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]},{"id":1641001,"name":"com.apple.coremedia.rootQueue.47","frames":[{"imageOffset":19004,"symbol":"semaphore_timedwait_trap","symbolLocation":8,"imageIndex":0},{"imageOffset":17908,"symbol":"_dispatch_sema4_timedwait","symbolLocation":64,"imageIndex":13},{"imageOffset":19444,"symbol":"_dispatch_semaphore_wait_slow","symbolLocation":76,"imageIndex":13},{"imageOffset":88128,"symbol":"_dispatch_worker_thread","symbolLocation":324,"imageIndex":13},{"imageOffset":5836,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":1},{"imageOffset":2980,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]},{"id":1641004,"name":"JavaScriptCore libpas scavenger","frames":[{"imageOffset":21372,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":0},{"imageOffset":32876,"symbol":"_pthread_cond_wait","symbolLocation":1232,"imageIndex":1},{"imageOffset":1008900,"symbol":"scavenger_thread_main","symbolLocation":1364,"imageIndex":14},{"imageOffset":5836,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":1},{"imageOffset":2980,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]},{"id":1641005,"name":"Heap Helper Thread","frames":[{"imageOffset":21372,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":0},{"imageOffset":32876,"symbol":"_pthread_cond_wait","symbolLocation":1232,"imageIndex":1},{"imageOffset":312924,"symbol":"WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&)","symbolLocation":1808,"imageIndex":14},{"imageOffset":53388,"symbol":"bool WTF::Condition::waitUntilUnchecked<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&)","symbolLocation":304,"imageIndex":14},{"imageOffset":54536,"symbol":"WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call()","symbolLocation":248,"imageIndex":14},{"imageOffset":454164,"symbol":"WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*)","symbolLocation":352,"imageIndex":14},{"imageOffset":463004,"symbol":"WTF::wtfThreadEntryPoint(void*)","symbolLocation":16,"imageIndex":14},{"imageOffset":5836,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":1},{"imageOffset":2980,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]},{"id":1641006,"name":"Heap Helper Thread","frames":[{"imageOffset":21372,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":0},{"imageOffset":32876,"symbol":"_pthread_cond_wait","symbolLocation":1232,"imageIndex":1},{"imageOffset":312924,"symbol":"WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&)","symbolLocation":1808,"imageIndex":14},{"imageOffset":53388,"symbol":"bool WTF::Condition::waitUntilUnchecked<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&)","symbolLocation":304,"imageIndex":14},{"imageOffset":54536,"symbol":"WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call()","symbolLocation":248,"imageIndex":14},{"imageOffset":454164,"symbol":"WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*)","symbolLocation":352,"imageIndex":14},{"imageOffset":463004,"symbol":"WTF::wtfThreadEntryPoint(void*)","symbolLocation":16,"imageIndex":14},{"imageOffset":5836,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":1},{"imageOffset":2980,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]},{"id":1641007,"name":"Heap Helper Thread","frames":[{"imageOffset":21372,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":0},{"imageOffset":32876,"symbol":"_pthread_cond_wait","symbolLocation":1232,"imageIndex":1},{"imageOffset":312924,"symbol":"WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&)","symbolLocation":1808,"imageIndex":14},{"imageOffset":53388,"symbol":"bool WTF::Condition::waitUntilUnchecked<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&)","symbolLocation":304,"imageIndex":14},{"imageOffset":54536,"symbol":"WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call()","symbolLocation":248,"imageIndex":14},{"imageOffset":454164,"symbol":"WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*)","symbolLocation":352,"imageIndex":14},{"imageOffset":463004,"symbol":"WTF::wtfThreadEntryPoint(void*)","symbolLocation":16,"imageIndex":14},{"imageOffset":5836,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":1},{"imageOffset":2980,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]},{"id":1641008,"name":"Heap Helper Thread","frames":[{"imageOffset":21372,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":0},{"imageOffset":32876,"symbol":"_pthread_cond_wait","symbolLocation":1232,"imageIndex":1},{"imageOffset":312924,"symbol":"WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&)","symbolLocation":1808,"imageIndex":14},{"imageOffset":53388,"symbol":"bool WTF::Condition::waitUntilUnchecked<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&)","symbolLocation":304,"imageIndex":14},{"imageOffset":54536,"symbol":"WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call()","symbolLocation":248,"imageIndex":14},{"imageOffset":454164,"symbol":"WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*)","symbolLocation":352,"imageIndex":14},{"imageOffset":463004,"symbol":"WTF::wtfThreadEntryPoint(void*)","symbolLocation":16,"imageIndex":14},{"imageOffset":5836,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":1},{"imageOffset":2980,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]},{"id":1641009,"name":"Heap Helper Thread","frames":[{"imageOffset":21372,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":0},{"imageOffset":32876,"symbol":"_pthread_cond_wait","symbolLocation":1232,"imageIndex":1},{"imageOffset":312924,"symbol":"WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&)","symbolLocation":1808,"imageIndex":14},{"imageOffset":53388,"symbol":"bool WTF::Condition::waitUntilUnchecked<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&)","symbolLocation":304,"imageIndex":14},{"imageOffset":54536,"symbol":"WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call()","symbolLocation":248,"imageIndex":14},{"imageOffset":454164,"symbol":"WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*)","symbolLocation":352,"imageIndex":14},{"imageOffset":463004,"symbol":"WTF::wtfThreadEntryPoint(void*)","symbolLocation":16,"imageIndex":14},{"imageOffset":5836,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":1},{"imageOffset":2980,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7609401344,
    "size" : 241636,
    "uuid" : "9daa5c29-93e0-3768-a3e1-e139995dc4af",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7885312000,
    "size" : 49152,
    "uuid" : "f2ba7ec0-f75a-3345-b4f6-f7da4979b902",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6700220416,
    "size" : 524280,
    "uuid" : "f088d98d-f2a1-3452-996f-9e6bb5139f52",
    "path" : "\/usr\/lib\/system\/libsystem_c.dylib",
    "name" : "libsystem_c.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7884480512,
    "size" : 98300,
    "uuid" : "a0028fdf-20f4-3a76-a43d-f0fa725bee9f",
    "path" : "\/usr\/lib\/libc++abi.dylib",
    "name" : "libc++abi.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6461554688,
    "size" : 278048,
    "uuid" : "d6ecfb73-0ca2-3a21-a3a9-19e450d3b49c",
    "path" : "\/usr\/lib\/libobjc.A.dylib",
    "name" : "libobjc.A.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6576095232,
    "size" : 4087808,
    "uuid" : "725e49f4-653b-39bf-9a7a-8a3250911ecb",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/CoreFoundation",
    "name" : "CoreFoundation"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7550050304,
    "size" : 36864,
    "uuid" : "5adda888-f387-35f7-87a7-e01fcb9bb928",
    "path" : "\/System\/Library\/PrivateFrameworks\/GraphicsServices.framework\/GraphicsServices",
    "name" : "GraphicsServices"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6611570688,
    "size" : 25083904,
    "uuid" : "59cbc9b5-30ae-396e-a269-a986640001bc",
    "path" : "\/System\/Library\/PrivateFrameworks\/UIKitCore.framework\/UIKitCore",
    "name" : "UIKitCore"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4301946880,
    "size" : 13352960,
    "uuid" : "8a68a1e5-e304-3358-ad1a-e6fcc2db849d",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/C2AE7A3D-01CC-4AD4-8227-F9DE4D7F94D8\/YouTube.app\/YouTube",
    "name" : "YouTube"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7088377856,
    "size" : 536720,
    "uuid" : "7b63c573-6161-3b33-a3a2-9944ba59722f",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6479122432,
    "size" : 9740288,
    "uuid" : "07a92f05-d8ec-327e-ab33-41db9f77ba16",
    "path" : "\/System\/Library\/Frameworks\/Foundation.framework\/Foundation",
    "name" : "Foundation"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4330602496,
    "size" : 107970560,
    "uuid" : "4ad358a6-030f-32dd-8f44-fd29a645f667",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/C2AE7A3D-01CC-4AD4-8227-F9DE4D7F94D8\/YouTube.app\/Frameworks\/Module_Framework.framework\/Module_Framework",
    "name" : "Module_Framework"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6594527232,
    "size" : 3973120,
    "uuid" : "8a75357d-7e21-3fb3-8b1e-4c0f63e8dc02",
    "path" : "\/System\/Library\/Frameworks\/CFNetwork.framework\/CFNetwork",
    "name" : "CFNetwork"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6699929600,
    "size" : 290816,
    "uuid" : "24db930d-870b-31ce-ac69-534d7896b4a8",
    "path" : "\/usr\/lib\/system\/libdispatch.dylib",
    "name" : "libdispatch.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6901825536,
    "size" : 21741568,
    "uuid" : "8c4289de-9d14-3823-86c8-c749af87c8da",
    "path" : "\/System\/Library\/Frameworks\/JavaScriptCore.framework\/JavaScriptCore",
    "name" : "JavaScriptCore"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4522115072,
    "size" : 49152,
    "uuid" : "376bab1e-0948-360f-a42b-92bf7f580158",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/C2AE7A3D-01CC-4AD4-8227-F9DE4D7F94D8\/YouTube.app\/Frameworks\/YouPiP.dylib",
    "name" : "YouPiP.dylib"
  }
],
  "sharedCache" : {
  "base" : 6460801024,
  "size" : 2921299968,
  "uuid" : "c4a46f4a-9b1a-3007-810f-2dabaec3b7fa"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.2G resident=0K(0%) swapped_out_or_unallocated=1.2G(100%)\nWritable regions: Total=929.6M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=929.6M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               128K        1 \nActivity Tracing                   256K        1 \nCG image                          4544K        6 \nCG raster data                    11.4M       53 \nColorSync                          496K       24 \nCoreAnimation                     2320K      126 \nCoreData                           176K        5 \nCoreData Object IDs               4112K        2 \nCoreUI image data                  192K        2 \nFoundation                         448K        4 \nImage IO                          5760K       17 \nKernel Alloc Once                   32K        1 \nMALLOC                           622.8M      394 \nMALLOC guard page                  192K       12 \nMach message                        16K        1 \nSQLite page cache                 2816K       22 \nSTACK GUARD                       1536K       33 \nStack                             19.4M       33 \nVM_ALLOCATE                        576K       11 \nWebKit Malloc                    192.1M        6 \nWebKit Malloc (reserved)          64.0M        1         reserved VM address space (unallocated)\n__AUTH                            3563K      478 \n__AUTH_CONST                      29.1M      738 \n__CTF                               756        1 \n__DATA                            47.6M      741 \n__DATA_CONST                      40.2M      751 \n__DATA_DIRTY                      3973K      640 \n__ETC                              112K        1 \n__FONT_DATA                        2352        1 \n__LINKEDIT                       327.3M       16 \n__OBJC_CONST                      6894K      510 \n__OBJC_RO                         78.7M        1 \n__OBJC_RW                         2434K        1 \n__TEXT                           874.0M      767 \ndyld private memory                256K        1 \nlibnetwork                        1664K       24 \nmapped file                      311.8M       63 \nshared memory                       48K        3 \n===========                     =======  ======= \nTOTAL                              2.6G     5492 \nTOTAL, minus reserved VM space     2.5G     5492 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "62b4513af75dc926494899c6",
      "factorPackIds" : {
        "COREOS_ICD" : "62b451816c843c3494e8dd8f"
      },
      "deploymentId" : 240000018
    },
    {
      "rolloutId" : "6010753cf9bfc4000c247bdd",
      "factorPackIds" : {
        "BIFROST_DEV_2" : "638e36d775b0720ff1f8c4de"
      },
      "deploymentId" : 240000255
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "660d93c8-d14c-49f9-ba7b-fc5b714585ca",
      "experimentId" : "6148ab04480ea0575d7a537c",
      "deploymentId" : 400000026
    },
    {
      "treatmentId" : "ed92c8ce-acec-433c-8f42-c832a816a20e",
      "experimentId" : "62cf21389a1c885618978432",
      "deploymentId" : 400000006
    }
  ]
}
}
```

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by PoomSmart** [comment]
Fixed with YouPiP 1.7.16

**Comment by difman62** [comment]
> Fixed with YouPiP 1.7.16

ok nice and how do I get this newer version into the app? Or we just wait for another new update altogether for the app?

**Comment by difman62** [comment]
oh nvm! Miraculously the PiP function worked without needing to do anything! Praise the devs, God bless.

**Comment by difman62** [comment]
Also, the button PiP (NOT uYouPIP) under the video player still crashes the whole app when clicked. Just letting you guys know about this.
![image](https://user-images.githubusercontent.com/121245283/209395850-90efad58-c2ac-4da9-bbbf-2a1dff746d87.png)

**Comment by qnblackcat** [comment]
YouPiP was updated to v1.7.16 in the newest release ([v17.49.6-2.1](https://github.com/qnblackcat/uYouPlus/releases/tag/v17.49.6-2.1))
